dj4e/firstdjwebsite/firstdjwebsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('firstsite.urls')),
    path('admin/', admin.site.urls),
]

dj4e/firstdjwebsite/firstsite/urls.py
from django.urls import path

from . import views

app_name = "firstsite"

urlpatterns = [
    #/
    path('', views.index, name='index'),
    #/music/
    path('music/', views.music, name='music'),
    #/music/[0-9]+
    path('music/<int:album_id>/', views.albums, name='album'),
    #/add/
    path('add', views.add, name='add')
]

dj4e/firstdjwebsite/firstsite/models.py
from django.db import models

# Create your models here.

dj4e/firstdjwebsite/firstsite/views.py
from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, Http404

from .models import Album

# Create your views here.

def index(request):
    #return HttpResponse('<h1>shipra chutiya<h1>') #for strings we use httpresponse
    replace = {'page_name':'Index page', 'msg':'bhai hai!!', 'char_page_name':'Sahil'}
    return render(request, 'index.html', replace) #for files containg html code etc

def add(request):
    result = int(request.POST['first_number'])+int(request.POST['second_number'])
    return render(request, 'result.htm', {'result':result})

def music(request):
    album_page = "<title> album page</title><h1> Albums </h1>"
    all_albums = Album.objects.all()
    for album in all_albums:
        album_link = '/' + str(album.id) + '/'
        #album_page += '<a href=' + album_link + '>' + str(album.album_title) + '</a><br />'
    parameters = {
        'all_albums':all_albums,
        'heading':'Album List',
        'page_name':'Album list page',
        'msg':'Nothing in the list'     
    }
    return render(request, 'music.html', parameters)

def albums(request, album_id):

    #try:
    #    album = .objects.get(pk=album_id)
    #except:
    #    raise Http404("File Does Not Exist!!!") # to raise a 404 error if an album is not found 
    
    # instead of using try and except you can also use the method get_object_or_404 
    
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'details.html', {'album':album, 'all_songs':album.song_set.all(), 'page_name':'Song page'})

dj4e/firstdjwebsite/templates/base.htm
<html>
    <head>
        <title>{{page_name}}</title>
    </head>
    <body style = "background:AliceBlue">
    {% block content %}
    
    {% endblock %}
    </body>
</html> 

dj4e/firstdjwebsite/templates/details.html
{% extends 'base.htm' %}

{% block content %}

    <title> {{ page_name }} </title>
    
    <h1> {{album.album_title}} </h1>
    <h3> Album artist: {{album.artist}} </h3>
    <h3> Album genre: {{album.genre}} </h3>
    <h3> Total songs: {{album.total_songs}} </h3>
    <!-- page styling -->
    <style>
        #song_table table{
            width : 50%;       
        }
        #song_table th{
            background : #000000;
            color : #ffffff;         
        }
        #song_table tr:nth-child(odd){
            background : #cccccc;        
        }
        #song_table table, td, th{
            border : 2px solid #a1a1a1;
            border-collapse : collapse;        
        }
        #song_table td, th{
            padding : 5px;
            text-align: center;
        }
    </style>
    
    {% if album.total_songs > 0 %}
    <div id="song_table" >
            <table>
                <tr>
                    <th>  Id </th>
                    <th> Title </th>
                    <th> File Type </th>
                </tr>
            {% for song in all_songs %}
                <tr style="text-align:center">    
                    <td> {{forloop.counter}} </td>
                    <td> {{song.song_title}} </td>
                    <td> {{song.file_type}} </td>
                </tr>
            {% endfor %}    
        
            </table>
            
            <br />
    </div>
    {% else %}
        
        <h3> No Songs In The DataBase </h3>
    
    {% endif %}

{% endblock%}

dj4e/firstdjwebsite/templates/index.html
{% extends 'base.htm' %} <!--django tag-->

{% block content %}   
    <h1>{{char_name}} {{msg}}!!!</h1>
    <br />
    <input type = 'button' value = '{{page_name}}' />
    <h1>SUM</h1>
    <form action = "add" method = 'post'>

        {% csrf_token %}<!-- must be used when using post method -->
    
        Enter The first number <input type = 'text' name = 'first_number' />
        <br />
        <br />
        Enter The second number <input type = 'text' name = 'second_number' />
        <br />
        <br />
        <input type = 'submit' value = 'ADD'>
    </form>
    <button > <a style="text-decoration:none" href = "{% url 'firstsite:music' %}" > Music Page </a> </button>
{% endblock%}

dj4e/firstdjwebsite/templates/music.html
{% extends 'base.htm' %}

{% block content %}
    

    {% if all_albums %}

        <h1> {{heading}} </h1>
    
        <ol>
            {% for album in all_albums %}
            <li> <a href = '{% url "firstsite:album" album.id %}' style="text-decoration:none"> {{album.album_title}} </a> </li><br />
            {% endfor %}    
        </ol>
    
    {% else %}
        <h1> {{msg}} </h1>
    {% endif %}

{% endblock %}

dj4e/firstdjwebsite/templates/result.htm
{% extends 'base.htm' %}

{% block content %}
    <h1>Result :- {{result}}</h1>
{% endblock %}